In [1]:
# WHAT IS TENSORFLOW ?? OPEN SOURCE END TO END ML LIBRARY FOR PREPROCSING DATA, MODELLING DATA 
# AND SERVING MODELS 

Jesse


In [2]:
# LEARNING OBJECTIVES 
# 1. INTRO TO TENSORS
# 2. TENSOR INFORMATION 
# 3. MANIPULATING TENSORS 
# 4. TENSORS VS NUMPY 
# 5. USING TF.FUNCTION AS A WAY TO SPEED UP PYTHON FUNCTIONS 
# 6. USING GPUs with Tensorflow 
# 7. EXERCISES 

In [43]:
# IMPORT TENSORFLOW 
import tensorflow as tf 
print(tf.__version__)

2.8.0


In [44]:
# CREATING TENSORS WITH TF.CONSTANT 
# tensorflow has built in modules (tf.io and tf.data) 
# this reads data sources and converts them to tensors 
# and then nueral network later processes them 

In [45]:
# WHAT IS A SCALAR ? IT IS A RANK 0 TENSOR THAT HAS NO DIMENSIONS (JUST A NUMBER) 
firstscalar = tf.constant(10) 
firstscalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [46]:
# IT HAS 0 DIMENSIONS BUT LETS CHECK THE DIMENSION 
firstscalar.ndim

0

In [47]:
# CREATE A VECTOR ? VECTOR HAS MORE THAN 0 DIMENSIONS ! HAS ONE DIMENSION OR AXIS 
firstvector = tf.constant([10, 10])
firstvector 
firstvector.ndim 

1

In [48]:
secondvector = tf.constant([10, 10, 10])
secondvector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [49]:
secondvector.ndim 

1

In [50]:
secondvector.shape 

TensorShape([3])

In [51]:
# MATRIX ?? MORE THAN ONE DIMENSION 
firstmatrix = tf.constant([[10, 7], 
                      [7, 10]])

In [52]:
firstmatrix 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [53]:
firstmatrix.ndim 

2

In [54]:
secondmatrix = tf.constant([[1, 2], 
                            [3, 4], 
                            [5, 6]])

In [55]:
secondmatrix.ndim 

2

In [56]:
thirdmatrix = tf.constant([[1, 2], 
                            [3, 4], 
                            [5, 6],
                            [7, 8]])

In [57]:
thirdmatrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [58]:
thirdmatrix.ndim 

2

In [59]:
# CREATE A TENSOR ?? WHICH HAS MORE THAN TWO DIMENSIONS 
firsttensor = tf.constant([[[1, 2, 3], 
                        [4, 5, 6]], 

                        [[7, 8, 9], 
                        [10, 11, 12]], 

                        [[13, 14, 15], 
                        [16, 17, 18]]])
firsttensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [60]:
firsttensor.ndim 

3

In [61]:
secondtensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9], 
   [10, 11, 12, 13, 14]],

  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19], 
   [20, 21, 22, 23, 24]],

  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29], 
   [28, 29, 30, 31, 32]],])
secondtensor

<tf.Tensor: shape=(3, 3, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [28, 29, 30, 31, 32]]], dtype=int32)>

In [62]:
secondtensor.ndim 

3

In [63]:
thirdmatrix = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(thirdmatrix)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [64]:
# A TENSOR CAN HAVE AN UNLIMITED AMOUNT OF DIMENSIONS 
# IE A SERIES OF IMAGES CAN BE TIRNED INTO TENSOR WITH SHAPE (224, 224, 3, 32)
# WHERE 244, 244,(FIRST 2 DIMENSIONS) ARE HEIGHT AND WIDTH OF THE IMAGES IN PIXELS 
# 3 is the number of color channels of the image(red, green and blue) 
# 32 is the batch size(number of images a nueral network sees at any one time)

In [65]:
# RECAP 
# SCALAR => A SINGLE NUMBER 
# VECTOR => A NUMBER WITH DIRECTION
# MATRIX => TWO D ARRAY OF NUMBERS 
# TENSOR => AN N DIMENSIONAL ARRAY OF NUMBERS 
# where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector

In [67]:
# CREATING TENSORS WITH TF.VARIABLE() & TF.CONSTANT 
firsttensor = tf.Variable([10, 7])
secondtensor = tf.constant([10, 7])
firsttensor, secondtensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [68]:
# TF.CONSTANT cannot be changed 
# for instance try and assign a tensor to secondtensor 
secondtensor[0] = 7 
secondtensor


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [70]:
# HOWEVER, TF.VARIABLE WILL WORK 
firsttensor[0].assign(7) 
firsttensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [71]:
# NOW LETS LOOK AT THE CONCEPT OF CREATING RANDOM TENSORS 
# random tensors are tensors of some arbitrary size which contains random numbers 
# random tensors are used by nueral networks to initialise weights(patterns) that are trying to learn data 
# 1. INITIALISE WITH RANDOM WEIGHTS(BEGINNING) -> SHOW EXAMPLES TO MODEL -> UPDATE -> REPEAT WITH MORE EXAMPLES 
# INPUTS -> NUMERICAL ENCODING -> LEARN REPRESENTATION(PATTERNS/FEATURES/WEIGHTS) -> OUTPUTS  

In [72]:
# CREATING A RANDOM TENSOR 
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 

random_1 = random_1.normal(shape=(3, 2)) # create tensor from normal distribution 

random_2 = tf.random.Generator.from_seed(42) 

random_2 = random_2.normal(shape=(3, 2)) 


In [73]:
# check if there are equal ? yes if a seed is set they will be equal 
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [81]:
# NOW WHAT WILL HAPPEN IS THE SEED IS CHANGED 
# CREATE A RANDOM SEED OF 42 AND 11 THAT TAKES THE SHAPE OF A 3, 2 
random_3 = tf.random.Generator.from_seed(42) 
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11) 
random_4 = random_4.normal(shape=(3, 2))

# now check for equality 
random_3, random_4, random_1 

# random_3 == random_3
random_3 == random_1
random_4 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [82]:
# MAIN GOAL OF THIS IS LETS SAY YOU ARE WORKING WITH 15,000 IMAGES OF CATS AND DOGS AND THE FIRST 10,000 IMAGES 
# ARE CATS AND 5,000 IMAGES ARE DOGS 
# IT IS A GOOD IDEA TO MOVE THE DATA AROUND AS THIS WILL AFFECT HOW A NN LEARNS 

In [91]:
# SHUFFLE THE TENSOR 
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
# gets different results each time 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [92]:
# why is the value above and below different ?? 
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [94]:
# set a global random seed 
tf.random.set_seed(42) 

# set the operation random seed 
tf.random.shuffle(not_shuffled, seed=42) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [96]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [97]:
# OTHER WAYS TO MAKE TENSORS 
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [98]:
# All zeros tensor 
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [99]:
# MAIN DIFFERENCE BETWEEN TENSORS AND NUMPY ARRAYS IS THAT TENSORS CAN RUN ON GPUs 

# GETTING INFORMATION FROM TENSORS(SHAPE, RANK AND SIZE) 
# SHAPE => THE LENGTH(NUMBER OF ELEMENT OF EACH OF THE DIMENSIONS OF A TENSOR)
# RANK => THE NUMBER OF TENSOR DIMENSIONS. A SCALAR HAS A RANK 0, VECTOR HAS A RANK 1, MATRIX RANK 2, TENSOR RANK N 
# AXIS OR DIMENSIONS => A PARTICULAR DIMENSION OF A TENSOR 
# SIZE => THE TOTAL NUMBER OF ITEMS IN THE TENSOR 

In [101]:
# CREATE A RANK 4 TENSOR 
rank4 = tf.zeros([2, 3, 4, 5, 6])
rank4 

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [102]:
rank4.shape, rank4.ndim, tf.size(rank4)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [103]:
# GET THE VARIOUS ATTRIBUTES OF THE TENSOR 
print("Datatype of every element:", rank4.dtype)
print("Number of dimensions (rank):", rank4.ndim)
print("Shape of tensor:", rank4.shape)
print("Elements along axis 0 of tensor:", rank4.shape[0])
print("Elements along last axis of tensor:", rank4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank4).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 5
Shape of tensor: (2, 3, 4, 5, 6)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 6
Total number of elements (2*3*4*5): 720


In [104]:
# GET THE FIRST 2 ITEMS OF EACH DIMENSIONS 
rank4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [105]:
# GET THE DIMENSION FROM EACH INDEX EXCEPT FOR THE FINAL ONE 
rank4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [107]:
# CREATE A RANK 2 TENSOR (2 DIMENSIONS) 
rank2 = tf.constant([[10, 7], [3, 4]])

# get the last item of each row 
rank2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [108]:
# ADD AN EXTRA DIMENSION (TO THE END) 
rank3 = rank2[..., tf.newaxis] # ... this means to all dimensions prior to 
rank2, rank3 # 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [109]:
tf.expand_dims(rank2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>