In [4]:
# WHAT IS TENSORFLOW ?? OPEN SOURCE END TO END ML LIBRARY FOR PREPROCSING DATA, MODELLING DATA 
# AND SERVING MODELS 

In [5]:
# LEARNING OBJECTIVES 
# 1. INTRO TO TENSORS
# 2. TENSOR INFORMATION 
# 3. MANIPULATING TENSORS 
# 4. TENSORS VS NUMPY 
# 5. USING TF.FUNCTION AS A WAY TO SPEED UP PYTHON FUNCTIONS 
# 6. USING GPUs with Tensorflow 
# 7. EXERCISES 

In [6]:
# IMPORT TENSORFLOW 
import tensorflow as tf 
print(tf.__version__)

2.8.0


In [7]:
# CREATING TENSORS WITH TF.CONSTANT 
# tensorflow has built in modules (tf.io and tf.data) 
# this reads data sources and converts them to tensors 
# and then nueral network later processes them 

In [8]:
# WHAT IS A SCALAR ? IT IS A RANK 0 TENSOR THAT HAS NO DIMENSIONS (JUST A NUMBER) 
firstscalar = tf.constant(10) 
firstscalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [9]:
# IT HAS 0 DIMENSIONS BUT LETS CHECK THE DIMENSION 
firstscalar.ndim

0

In [10]:
# CREATE A VECTOR ? VECTOR HAS MORE THAN 0 DIMENSIONS ! HAS ONE DIMENSION OR AXIS 
firstvector = tf.constant([10, 10])
firstvector 
firstvector.ndim 

1

In [11]:
secondvector = tf.constant([10, 10, 10])
secondvector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [12]:
secondvector.ndim 

1

In [13]:
secondvector.shape 

TensorShape([3])

In [14]:
# MATRIX ?? MORE THAN ONE DIMENSION 
firstmatrix = tf.constant([[10, 7], 
                      [7, 10]])

In [15]:
firstmatrix 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [16]:
firstmatrix.ndim 

2

In [17]:
secondmatrix = tf.constant([[1, 2], 
                            [3, 4], 
                            [5, 6]])

In [18]:
secondmatrix.ndim 

2

In [19]:
thirdmatrix = tf.constant([[1, 2], 
                            [3, 4], 
                            [5, 6],
                            [7, 8]])

In [20]:
thirdmatrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [21]:
thirdmatrix.ndim 

2

In [22]:
# CREATE A TENSOR ?? WHICH HAS MORE THAN TWO DIMENSIONS 
firsttensor = tf.constant([[[1, 2, 3], 
                        [4, 5, 6]], 

                        [[7, 8, 9], 
                        [10, 11, 12]], 

                        [[13, 14, 15], 
                        [16, 17, 18]]])
firsttensor 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [23]:
firsttensor.ndim 

3

In [24]:
secondtensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9], 
   [10, 11, 12, 13, 14]],

  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19], 
   [20, 21, 22, 23, 24]],

  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29], 
   [28, 29, 30, 31, 32]],])
secondtensor

<tf.Tensor: shape=(3, 3, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [28, 29, 30, 31, 32]]], dtype=int32)>

In [25]:
secondtensor.ndim 

3

In [26]:
thirdmatrix = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(thirdmatrix)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [27]:
# A TENSOR CAN HAVE AN UNLIMITED AMOUNT OF DIMENSIONS 
# IE A SERIES OF IMAGES CAN BE TIRNED INTO TENSOR WITH SHAPE (224, 224, 3, 32)
# WHERE 244, 244,(FIRST 2 DIMENSIONS) ARE HEIGHT AND WIDTH OF THE IMAGES IN PIXELS 
# 3 is the number of color channels of the image(red, green and blue) 
# 32 is the batch size(number of images a nueral network sees at any one time)

In [28]:
# RECAP 
# SCALAR => A SINGLE NUMBER 
# VECTOR => A NUMBER WITH DIRECTION
# MATRIX => TWO D ARRAY OF NUMBERS 
# TENSOR => AN N DIMENSIONAL ARRAY OF NUMBERS 
# where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector

In [29]:
# CREATING TENSORS WITH TF.VARIABLE() & TF.CONSTANT 
firsttensor = tf.Variable([10, 7])
secondtensor = tf.constant([10, 7])
firsttensor, secondtensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [30]:
# TF.CONSTANT cannot be changed 
# for instance try and assign a tensor to secondtensor 
secondtensor[0] = 7 
secondtensor


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [31]:
# HOWEVER, TF.VARIABLE WILL WORK 
firsttensor[0].assign(7) 
firsttensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [32]:
# NOW LETS LOOK AT THE CONCEPT OF CREATING RANDOM TENSORS 
# random tensors are tensors of some arbitrary size which contains random numbers 
# random tensors are used by nueral networks to initialise weights(patterns) that are trying to learn data 
# 1. INITIALISE WITH RANDOM WEIGHTS(BEGINNING) -> SHOW EXAMPLES TO MODEL -> UPDATE -> REPEAT WITH MORE EXAMPLES 
# INPUTS -> NUMERICAL ENCODING -> LEARN REPRESENTATION(PATTERNS/FEATURES/WEIGHTS) -> OUTPUTS  

In [33]:
# CREATING A RANDOM TENSOR 
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility 

random_1 = random_1.normal(shape=(3, 2)) # create tensor from normal distribution 

random_2 = tf.random.Generator.from_seed(42) 

random_2 = random_2.normal(shape=(3, 2)) 


In [34]:
# check if there are equal ? yes if a seed is set they will be equal 
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [35]:
# NOW WHAT WILL HAPPEN IS THE SEED IS CHANGED 
# CREATE A RANDOM SEED OF 42 AND 11 THAT TAKES THE SHAPE OF A 3, 2 
random_3 = tf.random.Generator.from_seed(42) 
random_3 = random_3.normal(shape=(3, 2))

random_4 = tf.random.Generator.from_seed(11) 
random_4 = random_4.normal(shape=(3, 2))

# now check for equality 
random_3, random_4, random_1 

# random_3 == random_3
random_3 == random_1
random_4 == random_3

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [36]:
# MAIN GOAL OF THIS IS LETS SAY YOU ARE WORKING WITH 15,000 IMAGES OF CATS AND DOGS AND THE FIRST 10,000 IMAGES 
# ARE CATS AND 5,000 IMAGES ARE DOGS 
# IT IS A GOOD IDEA TO MOVE THE DATA AROUND AS THIS WILL AFFECT HOW A NN LEARNS 

In [37]:
# SHUFFLE THE TENSOR 
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
# gets different results each time 
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [38]:
# why is the value above and below different ?? 
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [39]:
# set a global random seed 
tf.random.set_seed(42) 

# set the operation random seed 
tf.random.shuffle(not_shuffled, seed=42) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [40]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [41]:
# OTHER WAYS TO MAKE TENSORS 
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [42]:
# All zeros tensor 
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [43]:
# MAIN DIFFERENCE BETWEEN TENSORS AND NUMPY ARRAYS IS THAT TENSORS CAN RUN ON GPUs 

# GETTING INFORMATION FROM TENSORS(SHAPE, RANK AND SIZE) 
# SHAPE => THE LENGTH(NUMBER OF ELEMENT OF EACH OF THE DIMENSIONS OF A TENSOR)
# RANK => THE NUMBER OF TENSOR DIMENSIONS. A SCALAR HAS A RANK 0, VECTOR HAS A RANK 1, MATRIX RANK 2, TENSOR RANK N 
# AXIS OR DIMENSIONS => A PARTICULAR DIMENSION OF A TENSOR 
# SIZE => THE TOTAL NUMBER OF ITEMS IN THE TENSOR 

In [44]:
# CREATE A RANK 4 TENSOR 
rank4 = tf.zeros([2, 3, 4, 5, 6])
rank4 

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [45]:
rank4.shape, rank4.ndim, tf.size(rank4)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [46]:
# GET THE VARIOUS ATTRIBUTES OF THE TENSOR 
print("Datatype of every element:", rank4.dtype)
print("Number of dimensions (rank):", rank4.ndim)
print("Shape of tensor:", rank4.shape)
print("Elements along axis 0 of tensor:", rank4.shape[0])
print("Elements along last axis of tensor:", rank4.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank4).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 5
Shape of tensor: (2, 3, 4, 5, 6)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 6
Total number of elements (2*3*4*5): 720


In [47]:
# GET THE FIRST 2 ITEMS OF EACH DIMENSIONS 
rank4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [48]:
# GET THE DIMENSION FROM EACH INDEX EXCEPT FOR THE FINAL ONE 
rank4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [49]:
# CREATE A RANK 2 TENSOR (2 DIMENSIONS) 
rank2 = tf.constant([[10, 7], [3, 4]])

# get the last item of each row 
rank2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [50]:
# ADD AN EXTRA DIMENSION (TO THE END) 
rank3 = rank2[..., tf.newaxis] # ... this means to all dimensions prior to 
rank2, rank3 # 

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [51]:
tf.expand_dims(rank2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [52]:
# MANIPULATING TENSORS 
# FINDING PATTERNS IN TENSORS(NUMERICAL REP OF DATA) REQUIRES MANIPULATING THEM 


In [57]:
# BASIC OPERATIONS 
# using tf.constant means the original tensor is unchanged, the addition gets done on a copy 
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [58]:
tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [59]:
tensor * 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [60]:
# MATRIX MULTIPLICATION => TensorFlow implements this matrix multiplication functionality in the tf.matmul() method
# MAIN RULES for matrix multiplication to remember are 
# inner dimensions must match 
# (3, 5) @ (3, 5) wont work 
# (5, 3) @ (3, 5) will work
# (3, 5) @ (5, 3) will work

# resulting matrix has the shape of the outer dimensions 
# (5, 3) @ (3, 5) => (5, 5) 
# (3, 5) @ (5, 3) => (3, 3) 

In [61]:
# Matrix multiplication in tensorflow 
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [62]:
tf.matmul(tensor, tensor) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [63]:
tensor @ tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [64]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [65]:
X @ Y 

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [66]:
# either reshape X to (2, 3) so its (2, 3) @ (3, 2) 
# reshape Y to (3, 2) so its (3, 2) @ (2, 3) 
# i can use either tf.transpose() => switches the dimensions of a given tensor or tf.reshape() => allows us to reshape into a defined shape 

In [67]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [68]:
# Try matrix multipilication with reshaped Y 
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# use transpose 
tf.transpose(X) 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [70]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [71]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [72]:
# (3, 2) @ (2, 3) -> (3, 3) done with X @ tf.reshape(Y, shape=(2, 3)) 
# (2, 3) @ (3, 2) -> (2, 2) done with tf.matmul(tf.transpose(X), Y)

In [73]:
# This kind of data manipulation is a reminder: you'll spend a lot of your time in machine learning and working with 
# neural networks reshaping data (in the form of tensors) to prepare it to be used with various operations (such as feeding it to a model).

In [75]:
# DOT PRODUCT => CAN PERFORM THE TF.MATMUL() OPERATION USING TF.TENSORDOT() 
tf.tensordot(tf.transpose(X), Y, axes=1) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [76]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [77]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [80]:
# WE GET DIFFERENT VALUES 
# THIS IS STRANGE BCOS DEALING WITH Y a (3x2) matrix reshaping to (2, 3) and transposing it result in the same shape 
# Check shapes of Y, reshaped Y and Y and transposed Y 
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape 

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [81]:
# CALLING TF.RESHAPE() AND TF.TRANSPOSE() ON Y dont result in the same values 
print("Normal Y:")
print(Y, "\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 



In [83]:
print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, (2, 3)), "\n")

Y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 



In [84]:
print("Y transposed: ")
print(tf.transpose(Y))

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [85]:
# SOME EXPLANATIONS 
# tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12)
# tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.
# But generally, whenever performing a matrix multiplication and the shapes of two matrices don't line up, you will transpose (not reshape) one of them in order to line them up.

In [86]:
# CHANGING THE DATA TYPE OF THE TENSOR 
# sometimes alter the data type of a tensor 
# common when you want to compute using less precision numbers 
# computing with less precision numbers is useful on devices with less computing capacity such as mobile devices 

In [87]:
# CREATE A NEW TENSOR WITH DEFAULT DATA TYPE 
b = tf.constant([1.7, 7.4])

c = tf.constant([1, 7])
b, c 

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [88]:
# change from float32 to float 16 (reduced precision) 
c = tf.cast(c, dtype=tf.float32)
c 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [89]:
# getting the absolute value 
d = tf.constant([-7, -10])
d 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [90]:
tf.abs(d) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [92]:
# FINDING MIN, MAX, MEAN, SUM(AGGREGATION) 
# Create a tensor with 50 random values between 0 and 100
import numpy as np 
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([31,  4, 51, 30, 39,  1, 77, 74, 45, 22,  9, 93, 80, 81, 40, 27, 83,
       79, 67, 93, 74, 56,  1, 67, 74, 85, 41,  1, 90, 85, 76, 44, 99,  4,
       40, 77, 13,  0,  9, 85, 17, 43, 41, 21, 11, 17, 91, 75, 59, 22])>

In [93]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [94]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [95]:
# Find the mean
tf.reduce_mean(E)


<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [96]:
# Find the sum
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=int64, numpy=2444>

In [97]:
# ONE HOT ENCODING 
# If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().


In [98]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [99]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>

In [100]:
# MANIPULATING TF.VARIABLE TENSORS 
# ASSIGN() => assign a different value to a particular index of a variable tensor.
# ADD_ASSIGN() => add to an existing value and reassign it at a particular index of a variable tensor

In [101]:
i = tf.Variable(np.arange(0, 5)) 
i 

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [102]:
i.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [103]:
# add 10 to every element in i 
i.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [104]:
i 

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [105]:
# TENSORS VS NUMPY 
# TENSORS CAN BE CONVERTED TO NUMPY ARRAYS 
# NUMPY ARRAYS CAN CREATE TENSORS 

In [106]:
j = tf.constant(np.array([3., 7., 10.])) 
j 

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [108]:
# convert tensors to numpy 
np.array(j), type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [110]:
# Convert tensor J to NumPy with .numpy()
j.numpy(), type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [111]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [112]:
# USING TF.FUNCTION 
# In your TensorFlow adventures, you might come across Python functions which have the decorator @tf.function
# Its a decorator that modifies functions in another way 
# In the @tf.function decorator case, it turns a Python function into a callable TensorFlow graph. 
# Which is a fancy way of saying, if you've written your own Python function, and you decorate it with @tf.function, when you export your code (to potentially run on another device), 
# TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).



In [116]:
# create a simple function 
def function(x, y): 
    return x * y 

x = tf.constant(np.arange(0, 10))

y = tf.constant(np.arange(10, 20))

# function(x, y) 

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [117]:
x 

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [118]:
y 

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])>

In [119]:
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])>

In [120]:
# CREATE THE SAME FUNCTION AND DECORATE IT WITH TF.FUNCTION 
@tf.function 
def tf_function(x, y):
    return x * y 
tf_function(x, y) 

2022-05-07 20:49:30.241039: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


<tf.Tensor: shape=(10,), dtype=int64, numpy=array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])>